# This file was generated by GoReleaser. DO NOT EDIT.
cask "dbn-go-mcp-data" do
  name "dbn-go-mcp-data"
  desc "MCP Data Server for Databento's APIs"
  homepage "https://github.com/NimbleMarkets/dbn-go"
  version "0.8.10"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "bin/dbn-go-mcp-data"

  on_macos do
    on_intel do
      url "https://github.com/NimbleMarkets/dbn-go/releases/download/v#{version}/dbn-go-mcp-data_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/nimblemarkets/dbn-go"
      sha256 "44db83e181d9786d35e7b741b9792a53b66897b22bd7254502d0b023b013fd01"
    end
    on_arm do
      url "https://github.com/NimbleMarkets/dbn-go/releases/download/v#{version}/dbn-go-mcp-data_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/nimblemarkets/dbn-go"
      sha256 "ebd24ddeeb9a1eb95388380ef90aae7adb52f1042799d0928692cbde6a671adc"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/NimbleMarkets/dbn-go/releases/download/v#{version}/dbn-go-mcp-data_#{version}_linux_amd64.tar.gz",
        verified: "github.com/nimblemarkets/dbn-go"
      sha256 "283f83ea88000b1d951cda837500b8ee444c3beff1e32a4de865edea0637eb2a"
    end
    on_arm do
      url "https://github.com/NimbleMarkets/dbn-go/releases/download/v#{version}/dbn-go-mcp-data_#{version}_linux_arm64.tar.gz",
        verified: "github.com/nimblemarkets/dbn-go"
      sha256 "38b5d154042e5df830f5f9bb95a951eb41b52e722333d0dc459bf6e24ce95f67"
    end
  end

  # No zap stanza required
end
