# This file was generated by GoReleaser. DO NOT EDIT.
cask "dbn-go-mcp-data" do
  name "dbn-go-mcp-data"
  desc "MCP Data Server for Databento's APIs"
  homepage "https://github.com/NimbleMarkets/dbn-go"
  version "0.9.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "bin/dbn-go-mcp-data"

  on_macos do
    on_intel do
      url "https://github.com/NimbleMarkets/dbn-go/releases/download/v#{version}/dbn-go-mcp-data_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/nimblemarkets/dbn-go"
      sha256 "0f6d98ec07953b1acb793b3454e3363b5120f184afa3742413ff4a994cef2e0d"
    end
    on_arm do
      url "https://github.com/NimbleMarkets/dbn-go/releases/download/v#{version}/dbn-go-mcp-data_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/nimblemarkets/dbn-go"
      sha256 "38f7e91036caf674abe50e4628f852fc27d9a1fbac604b57526685c0349b003c"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/NimbleMarkets/dbn-go/releases/download/v#{version}/dbn-go-mcp-data_#{version}_linux_amd64.tar.gz",
        verified: "github.com/nimblemarkets/dbn-go"
      sha256 "fa1fff1f9fdda8f730a096102391b8c45abea929c3d6d4aa433ba9628bb8bbba"
    end
    on_arm do
      url "https://github.com/NimbleMarkets/dbn-go/releases/download/v#{version}/dbn-go-mcp-data_#{version}_linux_arm64.tar.gz",
        verified: "github.com/nimblemarkets/dbn-go"
      sha256 "dd60bf650d2fc0358fb77c484eca03c8fb3e59c4c7c3b198d99712e4d7780a12"
    end
  end

  # No zap stanza required
end
