# This file was generated by GoReleaser. DO NOT EDIT.
cask "ds4go" do
  version "0.5.0"

  on_macos do
    on_intel do
      sha256 "0a67a11ebdba5b700c329506e5198df187b9ee652b133a7500213379bec801ad"
      url "https://github.com/NimbleMarkets/ds4go/releases/download/v#{version}/ds4go_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "e3760fe39d746ed1bb5096c21ca41932caeaaf2582e321f66ad383ccdb2c09ab"
      url "https://github.com/NimbleMarkets/ds4go/releases/download/v#{version}/ds4go_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "10eca8cd0c883928eafc0bfb06cfc9595a5d3831db7defd1fdc81d27ab84ff38"
      url "https://github.com/NimbleMarkets/ds4go/releases/download/v#{version}/ds4go_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "babb0a11c74ab44df1989f9674c3241c16a8b8df5848221e7db566352af12a11"
      url "https://github.com/NimbleMarkets/ds4go/releases/download/v#{version}/ds4go_#{version}_linux_arm64.tar.gz"
    end
  end

  name "ds4go"
  desc "Pure-Go ds4 inference tooling for the DeepSeek-V4 engine"
  homepage "https://github.com/NimbleMarkets/ds4go"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ds4go"

  generate_completions_from_executable "ds4go", "completion",
    shell_parameter_format: :cobra

  # No zap stanza required

end
