# This file was generated by GoReleaser. DO NOT EDIT.
cask "ds4go" do
  version "0.5.1"

  on_macos do
    on_intel do
      sha256 "70d66a27f22a5f10371085520cc27d0a44a860501bea8019d3f043951b53619c"
      url "https://github.com/NimbleMarkets/ds4go/releases/download/v#{version}/ds4go_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "964bf9180e07beb83b74115904180d64126b2d3bbae51b8c1407ea8eaa84b60c"
      url "https://github.com/NimbleMarkets/ds4go/releases/download/v#{version}/ds4go_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "00456b4544140641d6ae323a85e9b51bc64900737aacd50b368268f3de049c4e"
      url "https://github.com/NimbleMarkets/ds4go/releases/download/v#{version}/ds4go_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "ab76c9f8a7aa49aea20f55c51737b0743697e84cb67c22bb4168876375ded15f"
      url "https://github.com/NimbleMarkets/ds4go/releases/download/v#{version}/ds4go_#{version}_linux_arm64.tar.gz"
    end
  end

  name "ds4go"
  desc "Pure-Go ds4 inference tooling for the DeepSeek-V4 engine"
  homepage "https://github.com/NimbleMarkets/ds4go"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ds4go"

  generate_completions_from_executable "ds4go", "completion",
    shell_parameter_format: :cobra

  # No zap stanza required

end
