# This file was generated by GoReleaser. DO NOT EDIT.
cask "ds4go" do
  version "0.4.0"

  on_macos do
    on_intel do
      sha256 "b1a64aff48045005d4e439dc11566709157af519e24807bacd7b21f9b8c695f6"
      url "https://github.com/NimbleMarkets/ds4go/releases/download/v#{version}/ds4go_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "0b458aec4b4f678ac8f039860ebd5d5750a4d01f137fc7379c47010ee1635f3a"
      url "https://github.com/NimbleMarkets/ds4go/releases/download/v#{version}/ds4go_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "c4b4673dc3dcdb11f90877e0dc150f1aecc2ea2ba9a9cf18fbd2ad82b607544a"
      url "https://github.com/NimbleMarkets/ds4go/releases/download/v#{version}/ds4go_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "5377413ec8da5f8c78b547ddfb1bfefcf8a90b05c25c09d293a7a0e2b65a4af4"
      url "https://github.com/NimbleMarkets/ds4go/releases/download/v#{version}/ds4go_#{version}_linux_arm64.tar.gz"
    end
  end

  name "ds4go"
  desc "Pure-Go ds4 inference tooling for the DeepSeek-V4 engine"
  homepage "https://github.com/NimbleMarkets/ds4go"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ds4go"

  generate_completions_from_executable "ds4go", "completion",
    shell_parameter_format: :cobra

  # No zap stanza required

end
