# This file was generated by GoReleaser. DO NOT EDIT.
cask "gloss" do
  version "0.2.0"

  on_macos do
    on_arm do
      sha256 "05e956aee439044347841f0f58e8d5980ca11639707b57aaeb724ffddef6e088"
      url "https://github.com/NimbleMarkets/gloss/releases/download/v#{version}/gloss_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "8634561c933cc383dffc053d7d6d4039ccdc6753bbfa4e7cf5be57ae9ba38dd5"
      url "https://github.com/NimbleMarkets/gloss/releases/download/v#{version}/gloss_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "8028cf75833d07de5f7c1218fe91101f0002bf5b35e7cd8f1ff710429d9f8a76"
      url "https://github.com/NimbleMarkets/gloss/releases/download/v#{version}/gloss_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "cc07bb58ec0ba09331a72c578de9ff1f50072873eec522c4ddb3b10ecb2de4f1"
      url "https://github.com/NimbleMarkets/gloss/releases/download/v#{version}/gloss_#{version}_linux_amd64.tar.gz"
    end
  end

  name "gloss"
  desc "Visual pager for the terminal, like less with pictures"
  homepage "https://nimblemarkets.github.io/gloss/"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "gloss"
  manpage "man/gloss.1"
  bash_completion "completions/gloss.bash"
  fish_completion "completions/gloss.fish"
  zsh_completion "completions/_gloss"

  # No zap stanza required
end
