# This file was generated by GoReleaser. DO NOT EDIT.
cask "gloss" do
  version "0.1.0"

  on_macos do
    on_arm do
      sha256 "a3433ca6e44e4344f04b832d4f370ad5e4cc360d7624e8c9560c6093c82c1018"
      url "https://github.com/NimbleMarkets/gloss/releases/download/v#{version}/gloss_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "67a478cdcd6213b6c7770b6db540f11bad49124951d43ad0ebaea7f5fa65ae95"
      url "https://github.com/NimbleMarkets/gloss/releases/download/v#{version}/gloss_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "ab4de6148e371a0f25947173913237a3ad421f12d101e37c5ecbbe2624df39a2"
      url "https://github.com/NimbleMarkets/gloss/releases/download/v#{version}/gloss_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "0dd52913b90d5c1b7adee3d18e4c99c8067afe33933e71332a72f6e2fbccf35a"
      url "https://github.com/NimbleMarkets/gloss/releases/download/v#{version}/gloss_#{version}_linux_amd64.tar.gz"
    end
  end

  name "gloss"
  desc "Visual pager for the terminal, like less with pictures"
  homepage "https://nimblemarkets.github.io/gloss/"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "gloss"

  # No zap stanza required
end
