# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class DbnGo < Formula
  desc "Golang tooling for Databento's APIs and DBN format"
  homepage "https://github.com/NimbleMarkets/dbn-go"
  version "0.4.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/NimbleMarkets/dbn-go/releases/download/v0.4.0/dbn-go_Darwin_x86_64.tar.gz"
      sha256 "d4d9a91330ce3d663ff23da1f4101c91ecc987928ef28f86f0313a2348307827"

      def install
        bin.install "./bin/dbn-go-file"
        bin.install "./bin/dbn-go-hist"
        bin.install "./bin/dbn-go-live"
        bin.install "./bin/dbn-go-tui"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/NimbleMarkets/dbn-go/releases/download/v0.4.0/dbn-go_Darwin_arm64.tar.gz"
      sha256 "dd51114dee267eb2cbe20faa9fda1959b19fa341df955c92a1eb19fa114910d0"

      def install
        bin.install "./bin/dbn-go-file"
        bin.install "./bin/dbn-go-hist"
        bin.install "./bin/dbn-go-live"
        bin.install "./bin/dbn-go-tui"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/NimbleMarkets/dbn-go/releases/download/v0.4.0/dbn-go_Linux_x86_64.tar.gz"
        sha256 "507dd6575f7963de24b79ee5162c5d7a328ba3083439310e7442a384aedac377"

        def install
          bin.install "./bin/dbn-go-file"
          bin.install "./bin/dbn-go-hist"
          bin.install "./bin/dbn-go-live"
          bin.install "./bin/dbn-go-tui"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/NimbleMarkets/dbn-go/releases/download/v0.4.0/dbn-go_Linux_arm64.tar.gz"
        sha256 "48a95b29bc6821dab3bc7569b2152925a09719f1609059c0af56ef5a310fb216"

        def install
          bin.install "./bin/dbn-go-file"
          bin.install "./bin/dbn-go-hist"
          bin.install "./bin/dbn-go-live"
          bin.install "./bin/dbn-go-tui"
        end
      end
    end
  end
end
