# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ds4go < Formula
  desc "Pure-Go ds4 inference tooling for the DeepSeek-V4 engine"
  homepage "https://github.com/NimbleMarkets/ds4go"
  version "0.2.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/NimbleMarkets/ds4go/releases/download/v0.2.3/ds4go_0.2.3_darwin_amd64.tar.gz"
      sha256 "e80cd81a215f1f5deb345ecfeb003c080f18bff71cd9fe7ee6a3152684ed3ced"

      define_method(:install) do
        bin.install "ds4go"
        generate_completions_from_executable(bin/"ds4go", "completion")
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/NimbleMarkets/ds4go/releases/download/v0.2.3/ds4go_0.2.3_darwin_arm64.tar.gz"
      sha256 "cda0e555c6351e444d8c0e1818212e426f2280f98dfe322a63a3661240126242"

      define_method(:install) do
        bin.install "ds4go"
        generate_completions_from_executable(bin/"ds4go", "completion")
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/NimbleMarkets/ds4go/releases/download/v0.2.3/ds4go_0.2.3_linux_amd64.tar.gz"
      sha256 "d90fb514265f1897e3bf9b18cc8aa9058af3acbb5ba2a3d41ed43ecab07333a2"
      define_method(:install) do
        bin.install "ds4go"
        generate_completions_from_executable(bin/"ds4go", "completion")
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/NimbleMarkets/ds4go/releases/download/v0.2.3/ds4go_0.2.3_linux_arm64.tar.gz"
      sha256 "18e3a43e674ca568ddc350cae5832cd7df0e1fffffc0e1b0cedb8983e498923a"
      define_method(:install) do
        bin.install "ds4go"
        generate_completions_from_executable(bin/"ds4go", "completion")
      end
    end
  end

  test do
    system "#{bin}/ds4go", "--help"
  end
end
