# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ollamatea < Formula
  desc "BubbleTea and Ollama components/tools"
  homepage "https://github.com/NimbleMarkets/ollamatea"
  version "0.0.1"

  on_macos do
    on_intel do
      url "https://github.com/NimbleMarkets/ollamatea/releases/download/0.0.1/ollamatea_Darwin_x86_64.tar.gz"
      sha256 "184e9f00eb4956517338f9cd6744c209f7b96245d9abc6067cb06b463da586c6"

      def install
        bin.install "./bin/ot-ansi-to-png"
        bin.install "./bin/ot-png-prompt"
        bin.install "./bin/ot-simplegen"
        bin.install "./bin/ot-timechart"
      end
    end
    on_arm do
      url "https://github.com/NimbleMarkets/ollamatea/releases/download/0.0.1/ollamatea_Darwin_arm64.tar.gz"
      sha256 "02797cd1f04055a6fbadf7c680cbdad43bf3246015e778bc9175d79bb4f27025"

      def install
        bin.install "./bin/ot-ansi-to-png"
        bin.install "./bin/ot-png-prompt"
        bin.install "./bin/ot-simplegen"
        bin.install "./bin/ot-timechart"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/NimbleMarkets/ollamatea/releases/download/0.0.1/ollamatea_Linux_x86_64.tar.gz"
        sha256 "d933598d7c22bb7c961dd9b1608ed7e63249df82eb4b383b65695f68507b20e9"

        def install
          bin.install "./bin/ot-ansi-to-png"
          bin.install "./bin/ot-png-prompt"
          bin.install "./bin/ot-simplegen"
          bin.install "./bin/ot-timechart"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/NimbleMarkets/ollamatea/releases/download/0.0.1/ollamatea_Linux_arm64.tar.gz"
        sha256 "e2e01f2f5c1bae0c18dfb73fed66e858c714e34b1af82faff3b8920644986cb8"

        def install
          bin.install "./bin/ot-ansi-to-png"
          bin.install "./bin/ot-png-prompt"
          bin.install "./bin/ot-simplegen"
          bin.install "./bin/ot-timechart"
        end
      end
    end
  end
end
